### ISSUE TITLE
__init__() missing 1 required positional argument: 'hparams'

### ISSUE THREAD

**Issue by Gauravchats** [chrishokamp/dynamic-transformer-ensembles#1]
While running the evaluation, I bumped into this error:

Traceback (most recent call last):
  File "transformer_decoding/evaluate.py", line 595, in <module>
    main(vars(parse_args()))
  File "transformer_decoding/evaluate.py", line 393, in main
    lightning_model = SummarizationTrainer.load_from_checkpoint(args['model_id'])
  File "/home/gaurav/.local/lib/python3.6/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/gaurav/.local/lib/python3.6/site-packages/pytorch_lightning/core/saving.py", line 199, in _load_model_state
    model = cls(**_cls_kwargs)
TypeError: __init__() missing 1 required positional argument: 'hparams'
Makefile:35: recipe for target 'evaluate' failed
make: *** [evaluate] Error 1

Please help!

**Comment by chrishokamp** [comment]
Apologies for late response, thanks for reporting -- I'll try to have a look at this this week

**Comment by chrishokamp** [comment]
@Gauravchats i pinned requirements, on the off chance you are still interested feel free to have another try, and reopen if you have issues
